### PR TITLE
Deep fix for #55

### LINKED ISSUE #55: Upgrade `Formulas` to `StatsModels` v0.6.0+
`StatsModels` v0.6.0 introduced a breaking redesign of its formulas which makes parts of `Bootstrap` incompatible with the latest versions of the package (see #52). Future versions of `Bootstrap` should adapt the new formula interface and become compatible with the lastest versions of `StatsModels`.

### PR DESCRIPTION
**Pull request by kleinschmidt**
This is a different approach to upgrading support for StatsModels to 0.6.  It
takes advantage of Terms 2.0 (Son of Terms) functionality by creating a special
Term type that wraps the left-hand side of the formula, and returns a sampled
version of the response variable every time it's asked to generate model
columns.  This allows the two separate methods for `bootstrap` using different
sampling strategies to be combined by factoring out the response re-sampling
into a single place.  More importantly, making the resampling step lazy in this
way removes all of the bookkeeping and copying of data, since the residuals are
resampled and added to the response at the last moment.

It also allows for any of the terms types supported by terms 2.0 to be used on
the LHS, including arbitrary functions.  So you can do things like
`@formula(log10(X) ~ log10(U))` and it will work (and the tests have been updated 
to reflect this)

fixes #55, fixes #56

### CODE REVIEW

**Comment by kleinschmidt** [comment]
Okay this is ready for review @juliangehring

File: src/bootsampling.jl [hunk 1]
```diff
@@ -337,55 +335,50 @@ function bootstrap(statistic::Function, data, model::SimpleModel, sampling::Boot
...
+# we only ever create one of these terms after the model has been fit once so we don't
+# need to create a new schema for it every time...
+StatsModels.needs_schema(t::ResidualTerm) = false
+StatsModels.termvars(t::ResidualTerm) = StatsModels.termvars(t.t)
+
 """
+bootstrap(statistic, data, model, formula, sampling)
 bootstrap(statistic, data, model, formula, Wildsampling(nrun, noise))
 """
-function bootstrap(statistic::Function, data::AbstractDataFrame, model::FormulaModel, sampling::WildSampling)
```
Comment (juliangehring) [inline src/bootsampling.jl]: Can we constrain `sampling <: ParametricSampling` here?

**Comment by juliangehring** [comment]
@kleinschmidt Thanks, this looks nice very! The review got a bit delayed due to holidays...

File: src/bootsampling.jl (hunk 1 above)
Comment (kleinschmidt) [reply src/bootsampling.jl]: You'd need to make Wild/ResidualSampling descendants of that though right?  RIght now they're both `<:BootstrapSampling` which is the supertype of Parametric (unless I'm missing something)

Comment (kleinschmidt) [reply src/bootsampling.jl]: Actually as far as I can tell nothing is `<:[Non]ParametricSampling` at the moment...

Comment (juliangehring) [reply src/bootsampling.jl]: Yeah, you are right. I wonder why `[Non]ParametricSampling` aren't used - maybe I forgot the use them in the signatures or I removed them partially at a later stage. I'll need to investigate this.
Can we then make it `<:BootstrapSampling`?

Comment (kleinschmidt) [reply src/bootsampling.jl]: Got it, just pushed that change

**Comment by nalimilan** [comment]
@juliangehring Any chance you could tag a new release? The StatsBase < 0.6 requirement seems to make Pkg fail to install StatsKit, which is really problematic (https://github.com/JuliaStats/StatsKit.jl/issues/20).

**Comment by juliangehring** [comment]
Should get fixed with v2.2.0 (see https://github.com/JuliaRegistries/General/pull/3230).
